<?php

namespace Database\Seeders;

use App\Models\ConsentFormQuestion;
use Illuminate\Database\Seeder;

class ConsentFormQuestionSeeder extends Seeder
{
    /**
     * Seed default consent form questions for user_id 1.
     * Content taken from public/data/consent-default-items-strings.json
     * and embedded here (not loaded from the file at runtime).
     */
    public function run(): void
    {
        $userId = 1;

        $questions = array (
  0 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Heart condition, pacemaker, or heart surgery history',
      'de' => 'Herzerkrankung, Herzschrittmacher oder Herzoperation in der Vorgeschichte',
      'nl' => 'Hartaandoening, pacemaker of eerdere hartoperatie',
      'fr' => 'Maladie cardiaque, stimulateur cardiaque ou antécédent de chirurgie cardiaque',
      'es' => 'Enfermedad cardíaca, marcapasos o antecedentes de cirugía cardíaca',
      'it' => 'Cardiopatia, pacemaker o precedente intervento chirurgico al cuore',
      'el' => 'Καρδιακή πάθηση, βηματοδότης ή ιστορικό καρδιοχειρουργικής επέμβασης',
      'pt' => 'Doença cardíaca, pacemaker ou histórico de cirurgia cardíaca',
      'sv' => 'Hjärtsjukdom, pacemaker eller tidigare hjärtoperation',
      'da' => 'Hjertesygdom, pacemaker eller tidligere hjerteoperation',
      'fi' => 'Sydänsairaus, tahdistin tai aiempi sydänleikkaus',
      'no' => 'Hjertesykdom, pacemaker eller tidligere hjerteoperasjon',
      'pl' => 'Choroba serca, rozrusznik serca lub przebyta operacja serca',
      'cs' => 'Srdeční onemocnění, kardiostimulátor nebo operace srdce v anamnéze',
      'sk' => 'Srdcové ochorenie, kardiostimulátor alebo operácia srdca v anamnéze',
      'hu' => 'Szívbetegség, szívritmus-szabályozó vagy korábbi szívműtét',
      'ro' => 'Afecțiune cardiacă, stimulator cardiac sau intervenție chirurgicală cardiacă în antecedente',
      'bg' => 'Сърдечно заболяване, пейсмейкър или сърдечна операция в миналото',
      'hr' => 'Srčana bolest, elektrostimulator srca ili prethodna operacija srca',
      'sl' => 'Srčna bolezen, srčni spodbujevalnik ali predhodna operacija srca',
      'et' => 'Südamehaigus, südamestimulaator või varasem südameoperatsioon',
      'lv' => 'Sirds slimība, elektrokardiostimulators vai iepriekšēja sirds operācija',
      'lt' => 'Širdies liga, širdies stimuliatorius ar ankstesnė širdies operacija',
    ),
    'enabled' => true,
  ),
  1 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Diabetes (Type 1 or Type 2)',
      'de' => 'Diabetes (Typ 1 oder Typ 2)',
      'nl' => 'Diabetes (type 1 of type 2)',
      'fr' => 'Diabète (type 1 ou type 2)',
      'es' => 'Diabetes (Tipo 1 o Tipo 2)',
      'it' => 'Diabete (Tipo 1 o Tipo 2)',
      'el' => 'Διαβήτης (Τύπου 1 ή 2)',
      'pt' => 'Diabetes (Tipo 1 ou Tipo 2)',
      'sv' => 'Diabetes (typ 1 eller typ 2)',
      'da' => 'Diabetes (type 1 eller type 2)',
      'fi' => 'Diabetes (tyyppi 1 tai 2)',
      'no' => 'Diabetes (type 1 eller type 2)',
      'pl' => 'Cukrzyca (typu 1 lub typu 2)',
      'cs' => 'Diabetes (1. nebo 2. typu)',
      'sk' => 'Diabetes (1. alebo 2. typu)',
      'hu' => 'Cukorbetegség (1-es vagy 2-es típusú)',
      'ro' => 'Diabet (tip 1 sau tip 2)',
      'bg' => 'Диабет (тип 1 или тип 2)',
      'hr' => 'Dijabetes (tip 1 ili tip 2)',
      'sl' => 'Sladkorna bolezen (tip 1 ali tip 2)',
      'et' => 'Diabeet (1. või 2. tüüpi)',
      'lv' => 'Diabēts (1. vai 2. tips)',
      'lt' => 'Diabetas (1 ar 2 tipo)',
    ),
    'enabled' => true,
  ),
  2 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Haemophilia or other bleeding disorder',
      'de' => 'Hämophilie oder andere Blutgerinnungsstörung',
      'nl' => 'Hemofilie of andere bloedstollingsstoornis',
      'fr' => 'Hémophilie ou autre trouble de la coagulation',
      'es' => 'Hemofilia u otro trastorno de coagulación',
      'it' => 'Emofilia o altro disturbo della coagulazione',
      'el' => 'Αιμορροφιλία ή άλλη διαταραχή πήξης',
      'pt' => 'Hemofilia ou outra doença de coagulação',
      'sv' => 'Hemofili eller annan blödarsjuka',
      'da' => 'Hæmofili eller anden blødningsforstyrrelse',
      'fi' => 'Hemofilia tai muu verenvuotohäiriö',
      'no' => 'Hemofili eller annen blødningssykdom',
      'pl' => 'Hemofilia lub inne zaburzenie krzepnięcia',
      'cs' => 'Hemofilie nebo jiná porucha srážlivosti krve',
      'sk' => 'Hemofília alebo iná porucha zrážanlivosti krvi',
      'hu' => 'Vérzékenység vagy más véralvadási zavar',
      'ro' => 'Hemofilie sau altă tulburare de coagulare',
      'bg' => 'Хемофилия или друго нарушение на кръвосъсирването',
      'hr' => 'Hemofilija ili drugi poremećaj zgrušavanja krvi',
      'sl' => 'Hemofilija ali druga motnja strjevanja krvi',
      'et' => 'Hemofiilia või muu verehüübimishäire',
      'lv' => 'Hemofīlija vai cits asins recēšanas traucējums',
      'lt' => 'Hemofilija ar kitas kraujo krešėjimo sutrikimas',
    ),
    'enabled' => true,
  ),
  3 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Currently pregnant or breastfeeding',
      'de' => 'Derzeit schwanger oder stillend',
      'nl' => 'Momenteel zwanger of borstvoeding',
      'fr' => 'Actuellement enceinte ou allaitante',
      'es' => 'Actualmente embarazada o en periodo de lactancia',
      'it' => 'Attualmente incinta o in allattamento',
      'el' => 'Είστε αυτή τη στιγμή έγκυος ή θηλάζετε',
      'pt' => 'Atualmente grávida ou a amamentar',
      'sv' => 'Gravid eller ammar för närvarande',
      'da' => 'Gravid eller ammer i øjeblikket',
      'fi' => 'Raskaana tai imettää tällä hetkellä',
      'no' => 'Gravid eller ammer for tiden',
      'pl' => 'Obecnie w ciąży lub karmiąca piersią',
      'cs' => 'Aktuálně těhotná nebo kojící',
      'sk' => 'Aktuálne tehotná alebo dojčiaca',
      'hu' => 'Jelenleg terhes vagy szoptat',
      'ro' => 'În prezent însărcinată sau alăptează',
      'bg' => 'В момента бременна или кърми',
      'hr' => 'Trenutno trudna ili doji',
      'sl' => 'Trenutno noseča ali doji',
      'et' => 'Praegu rase või imetab',
      'lv' => 'Pašlaik grūtniece vai baro bērnu ar krūti',
      'lt' => 'Šiuo metu nėščia arba žindo',
    ),
    'enabled' => true,
  ),
  4 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Epilepsy or seizure history',
      'de' => 'Epilepsie oder Anfallsleiden in der Vorgeschichte',
      'nl' => 'Epilepsie of eerdere toevallen',
      'fr' => 'Épilepsie ou antécédent de crises',
      'es' => 'Epilepsia o antecedentes de convulsiones',
      'it' => 'Epilessia o precedenti crisi convulsive',
      'el' => 'Επιληψία ή ιστορικό σπασμών',
      'pt' => 'Epilepsia ou histórico de convulsões',
      'sv' => 'Epilepsi eller tidigare krampanfall',
      'da' => 'Epilepsi eller tidligere krampeanfald',
      'fi' => 'Epilepsia tai aiempi kohtaushistoria',
      'no' => 'Epilepsi eller tidligere anfall',
      'pl' => 'Padaczka lub napady drgawkowe w wywiadzie',
      'cs' => 'Epilepsie nebo záchvaty v anamnéze',
      'sk' => 'Epilepsia alebo záchvaty v anamnéze',
      'hu' => 'Epilepszia vagy korábbi rohamok',
      'ro' => 'Epilepsie sau antecedente de convulsii',
      'bg' => 'Епилепсия или анамнеза за припадъци',
      'hr' => 'Epilepsija ili prethodni napadaji',
      'sl' => 'Epilepsija ali predhodni napadi',
      'et' => 'Epilepsia või varasemad krambid',
      'lv' => 'Epilepsija vai iepriekšēji krampji',
      'lt' => 'Epilepsija ar ankstesni priepuoliai',
    ),
    'enabled' => true,
  ),
  5 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'HIV, hepatitis B, or hepatitis C',
      'de' => 'HIV, Hepatitis B oder Hepatitis C',
      'nl' => 'Hiv, hepatitis B of hepatitis C',
      'fr' => 'VIH, hépatite B ou hépatite C',
      'es' => 'VIH, hepatitis B o hepatitis C',
      'it' => 'HIV, epatite B o epatite C',
      'el' => 'HIV, ηπατίτιδα B ή ηπατίτιδα C',
      'pt' => 'VIH, hepatite B ou hepatite C',
      'sv' => 'HIV, hepatit B eller hepatit C',
      'da' => 'HIV, hepatitis B eller hepatitis C',
      'fi' => 'HIV, hepatiitti B tai hepatiitti C',
      'no' => 'HIV, hepatitt B eller hepatitt C',
      'pl' => 'HIV, WZW typu B lub WZW typu C',
      'cs' => 'HIV, hepatitida B nebo hepatitida C',
      'sk' => 'HIV, hepatitída B alebo hepatitída C',
      'hu' => 'HIV, hepatitis B vagy hepatitis C',
      'ro' => 'HIV, hepatita B sau hepatita C',
      'bg' => 'ХИВ, хепатит B или хепатит C',
      'hr' => 'HIV, hepatitis B ili hepatitis C',
      'sl' => 'HIV, hepatitis B ali hepatitis C',
      'et' => 'HIV, B-hepatiit või C-hepatiit',
      'lv' => 'HIV, B hepatīts vai C hepatīts',
      'lt' => 'ŽIV, B hepatitas ar C hepatitas',
    ),
    'enabled' => true,
  ),
  6 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Active skin condition at or near the tattoo site',
      'de' => 'Aktive Hauterkrankung an oder in der Nähe der Tattoo-Stelle',
      'nl' => 'Actieve huidaandoening op of nabij de tatoeageplek',
      'fr' => 'Affection cutanée active sur ou près de la zone à tatouer',
      'es' => 'Afección cutánea activa en la zona del tatuaje o cerca de ella',
      'it' => 'Condizione cutanea attiva sulla o vicino alla zona del tatuaggio',
      'el' => 'Ενεργή δερματική πάθηση κοντά στην περιοχή του τατουάζ',
      'pt' => 'Condição cutânea ativa no local da tatuagem ou perto dele',
      'sv' => 'Aktiv hudåkomma på eller nära tatueringsstället',
      'da' => 'Aktiv hudlidelse på eller nær tatoveringsstedet',
      'fi' => 'Aktiivinen ihosairaus tatuointikohdassa tai sen lähellä',
      'no' => 'Aktiv hudlidelse på eller nær tatoveringsstedet',
      'pl' => 'Aktywna choroba skóry w miejscu tatuażu lub w jego pobliżu',
      'cs' => 'Aktivní kožní onemocnění v místě tetování nebo poblíž',
      'sk' => 'Aktívne kožné ochorenie v mieste tetovania alebo v jeho blízkosti',
      'hu' => 'Aktív bőrbetegség a tetoválás helyén vagy annak közelében',
      'ro' => 'Afecțiune cutanată activă la sau lângă locul tatuajului',
      'bg' => 'Активно кожно заболяване на или близо до мястото на татуировката',
      'hr' => 'Aktivna kožna bolest na mjestu tetovaže ili blizu njega',
      'sl' => 'Aktivna kožna bolezen na mestu tetovaže ali v njeni bližini',
      'et' => 'Aktiivne nahahaigus tätoveeringu kohas või selle läheduses',
      'lv' => 'Aktīva ādas slimība tetovējuma vietā vai tās tuvumā',
      'lt' => 'Aktyvi odos liga tatuiruotės vietoje ar arti jos',
    ),
    'enabled' => true,
  ),
  7 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Blood thinners, aspirin, or ibuprofen in the last 24 hours',
      'de' => 'Blutverdünner, Aspirin oder Ibuprofen in den letzten 24 Stunden',
      'nl' => 'Bloedverdunners, aspirine of ibuprofen in de afgelopen 24 uur',
      'fr' => 'Anticoagulants, aspirine ou ibuprofène au cours des 24 dernières heures',
      'es' => 'Anticoagulantes, aspirina o ibuprofeno en las últimas 24 horas',
      'it' => 'Anticoagulanti, aspirina o ibuprofene nelle ultime 24 ore',
      'el' => 'Αντιπηκτικά, ασπιρίνη ή ιμπουπροφαίνη τις τελευταίες 24 ώρες',
      'pt' => 'Anticoagulantes, aspirina ou ibuprofeno nas últimas 24 horas',
      'sv' => 'Blodförtunnande medel, aspirin eller ibuprofen de senaste 24 timmarna',
      'da' => 'Blodfortyndende medicin, aspirin eller ibuprofen inden for de sidste 24 timer',
      'fi' => 'Verenohennuslääkkeitä, aspiriinia tai ibuprofeenia viimeisen 24 tunnin aikana',
      'no' => 'Blodfortynnende midler, aspirin eller ibuprofen de siste 24 timene',
      'pl' => 'Leki rozrzedzające krew, aspiryna lub ibuprofen w ciągu ostatnich 24 godzin',
      'cs' => 'Léky na ředění krve, aspirin nebo ibuprofen za posledních 24 hodin',
      'sk' => 'Lieky na riedenie krvi, aspirín alebo ibuprofén za posledných 24 hodín',
      'hu' => 'Vérhígítók, aszpirin vagy ibuprofen az elmúlt 24 órában',
      'ro' => 'Anticoagulante, aspirină sau ibuprofen în ultimele 24 de ore',
      'bg' => 'Антикоагуланти, аспирин или ибупрофен през последните 24 часа',
      'hr' => 'Antikoagulansi, aspirin ili ibuprofen u posljednja 24 sata',
      'sl' => 'Antikoagulanti, aspirin ali ibuprofen v zadnjih 24 urah',
      'et' => 'Verd vedeldavad ravimid, aspiriin või ibuprofeen viimase 24 tunni jooksul',
      'lv' => 'Asinis šķidrinoši medikamenti, aspirīns vai ibuprofēns pēdējo 24 stundu laikā',
      'lt' => 'Kraują skystinantys vaistai, aspirinas ar ibuprofenas per pastarąsias 24 valandas',
    ),
    'enabled' => true,
  ),
  8 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Alcohol or recreational drugs in the last 24 hours',
      'de' => 'Alkohol oder Freizeitdrogen in den letzten 24 Stunden',
      'nl' => 'Alcohol of recreatieve drugs in de afgelopen 24 uur',
      'fr' => 'Alcool ou drogues récréatives au cours des 24 dernières heures',
      'es' => 'Alcohol o drogas recreativas en las últimas 24 horas',
      'it' => 'Alcol o droghe ricreative nelle ultime 24 ore',
      'el' => 'Αλκοόλ ή ουσίες τις τελευταίες 24 ώρες',
      'pt' => 'Álcool ou drogas recreativas nas últimas 24 horas',
      'sv' => 'Alkohol eller droger de senaste 24 timmarna',
      'da' => 'Alkohol eller rusmidler inden for de sidste 24 timer',
      'fi' => 'Alkoholia tai huumeita viimeisen 24 tunnin aikana',
      'no' => 'Alkohol eller rusmidler de siste 24 timene',
      'pl' => 'Alkohol lub substancje rekreacyjne w ciągu ostatnich 24 godzin',
      'cs' => 'Alkohol nebo rekreační drogy za posledních 24 hodin',
      'sk' => 'Alkohol alebo rekreačné drogy za posledných 24 hodín',
      'hu' => 'Alkohol vagy szórakoztató célú drogok az elmúlt 24 órában',
      'ro' => 'Alcool sau droguri recreaționale în ultimele 24 de ore',
      'bg' => 'Алкохол или наркотични вещества през последните 24 часа',
      'hr' => 'Alkohol ili rekreativne droge u posljednja 24 sata',
      'sl' => 'Alkohol ali rekreativne droge v zadnjih 24 urah',
      'et' => 'Alkohol või meelelahutuslikud narkootikumid viimase 24 tunni jooksul',
      'lv' => 'Alkohols vai atpūtas narkotikas pēdējo 24 stundu laikā',
      'lt' => 'Alkoholis ar rekreaciniai narkotikai per pastarąsias 24 valandas',
    ),
    'enabled' => true,
  ),
  9 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Prior allergic reaction to tattoo ink or pigment',
      'de' => 'Frühere allergische Reaktion auf Tattoo-Tinte oder Pigment',
      'nl' => 'Eerdere allergische reactie op tatoeage-inkt of pigment',
      'fr' => 'Réaction allergique antérieure à l\'encre ou au pigment de tatouage',
      'es' => 'Reacción alérgica previa a la tinta o pigmento del tatuaje',
      'it' => 'Precedente reazione allergica all\'inchiostro o al pigmento del tatuaggio',
      'el' => 'Προηγούμενη αλλεργική αντίδραση σε μελάνι ή χρωστική τατουάζ',
      'pt' => 'Reação alérgica anterior à tinta ou pigmento da tatuagem',
      'sv' => 'Tidigare allergisk reaktion mot tatueringsbläck eller pigment',
      'da' => 'Tidligere allergisk reaktion på tatoveringsblæk eller pigment',
      'fi' => 'Aiempi allerginen reaktio tatuointimusteelle tai pigmentille',
      'no' => 'Tidligere allergisk reaksjon på tatoveringsblekk eller pigment',
      'pl' => 'Wcześniejsza reakcja alergiczna na tusz lub pigment do tatuażu',
      'cs' => 'Předchozí alergická reakce na tetovací inkoust nebo pigment',
      'sk' => 'Predchádzajúca alergická reakcia na tetovací atrament alebo pigment',
      'hu' => 'Korábbi allergiás reakció tetoválótintára vagy pigmentre',
      'ro' => 'Reacție alergică anterioară la cerneala sau pigmentul de tatuaj',
      'bg' => 'Предишна алергична реакция към мастило или пигмент за татуировка',
      'hr' => 'Prethodna alergijska reakcija na tintu ili pigment za tetoviranje',
      'sl' => 'Predhodna alergijska reakcija na tetovažno tinto ali pigment',
      'et' => 'Varasem allergiline reaktsioon tätoveerimistindile või pigmendile',
      'lv' => 'Iepriekšēja alerģiska reakcija uz tetovējuma tinti vai pigmentu',
      'lt' => 'Ankstesnė alerginė reakcija į tatuiruotės rašalą ar pigmentą',
    ),
    'enabled' => true,
  ),
  10 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Latex allergy',
      'de' => 'Latexallergie',
      'nl' => 'Latexallergie',
      'fr' => 'Allergie au latex',
      'es' => 'Alergia al látex',
      'it' => 'Allergia al lattice',
      'el' => 'Αλλεργία σε λάτεξ',
      'pt' => 'Alergia ao látex',
      'sv' => 'Latexallergi',
      'da' => 'Latexallergi',
      'fi' => 'Lateksiallergia',
      'no' => 'Lateksallergi',
      'pl' => 'Alergia na lateks',
      'cs' => 'Alergie na latex',
      'sk' => 'Alergia na latex',
      'hu' => 'Latexallergia',
      'ro' => 'Alergie la latex',
      'bg' => 'Алергия към латекс',
      'hr' => 'Alergija na lateks',
      'sl' => 'Alergija na lateks',
      'et' => 'Lateksiallergia',
      'lv' => 'Alerģija pret lateksu',
      'lt' => 'Alergija lateksui',
    ),
    'enabled' => true,
  ),
  11 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'History of keloid or hypertrophic scarring',
      'de' => 'Vorgeschichte von Keloid- oder hypertropher Narbenbildung',
      'nl' => 'Voorgeschiedenis van keloïd- of hypertrofische littekens',
      'fr' => 'Antécédent de cicatrices chéloïdes ou hypertrophiques',
      'es' => 'Antecedentes de cicatrices queloides o hipertróficas',
      'it' => 'Precedenti cicatrici cheloidi o ipertrofiche',
      'el' => 'Ιστορικό χηλοειδών ή υπερτροφικών ουλών',
      'pt' => 'Histórico de cicatrizes queloides ou hipertróficas',
      'sv' => 'Tidigare keloid- eller hypertrofisk ärrbildning',
      'da' => 'Tidligere keloid- eller hypertrofisk arvæv',
      'fi' => 'Aiempi keloidi- tai hypertrofinen arpeutuminen',
      'no' => 'Tidligere keloid- eller hypertrofisk arrdannelse',
      'pl' => 'Bliznowce lub blizny przerostowe w wywiadzie',
      'cs' => 'Keloidní nebo hypertrofické jizvy v anamnéze',
      'sk' => 'Keloidné alebo hypertrofické jazvy v anamnéze',
      'hu' => 'Keloid vagy hipertrófiás hegképződés a kórelőzményben',
      'ro' => 'Antecedente de cicatrici cheloide sau hipertrofice',
      'bg' => 'Анамнеза за келоидни или хипертрофични белези',
      'hr' => 'Prethodni keloidni ili hipertrofični ožiljci',
      'sl' => 'Predhodne keloidne ali hipertrofične brazgotine',
      'et' => 'Varasem keloidarm või hüpertroofiline arm',
      'lv' => 'Iepriekšēji keloīda vai hipertrofiski rētas',
      'lt' => 'Ankstesni keloidiniai ar hipertrofiniai randai',
    ),
    'enabled' => true,
  ),
  12 => 
  array (
    'question_type' => 'health',
    'translations' => 
    array (
      'en' => 'Roaccutane or other photosensitising medication in the last 6 months',
      'de' => 'Roaccutan oder andere photosensibilisierende Medikamente in den letzten 6 Monaten',
      'nl' => 'Roaccutane of andere fotosensibiliserende medicatie in de afgelopen 6 maanden',
      'fr' => 'Roaccutane ou autre médicament photosensibilisant au cours des 6 derniers mois',
      'es' => 'Roaccutane u otro medicamento fotosensibilizante en los últimos 6 meses',
      'it' => 'Roaccutan o altro farmaco fotosensibilizzante negli ultimi 6 mesi',
      'el' => 'Roaccutane ή άλλη φωτοευαισθητοποιητική αγωγή τους τελευταίους 6 μήνες',
      'pt' => 'Roacutan ou outro medicamento fotossensibilizante nos últimos 6 meses',
      'sv' => 'Roaccutan eller annan ljuskänslighetsframkallande medicin de senaste 6 månaderna',
      'da' => 'Roaccutan eller anden fotosensibiliserende medicin inden for de sidste 6 måneder',
      'fi' => 'Roaccutane tai muu valoherkkyyttä aiheuttava lääkitys viimeisen 6 kuukauden aikana',
      'no' => 'Roaccutan eller annen fotosensibiliserende medisin de siste 6 månedene',
      'pl' => 'Roaccutane lub inny lek fotouczulający w ciągu ostatnich 6 miesięcy',
      'cs' => 'Roaccutane nebo jiný fotosenzibilizující lék za posledních 6 měsíců',
      'sk' => 'Roaccutane alebo iný fotosenzibilizujúci liek za posledných 6 mesiacov',
      'hu' => 'Roaccutane vagy más fényérzékenyítő gyógyszer az elmúlt 6 hónapban',
      'ro' => 'Roaccutane sau alt medicament fotosensibilizant în ultimele 6 luni',
      'bg' => 'Роакутан или друго фотосенсибилизиращо лекарство през последните 6 месеца',
      'hr' => 'Roaccutane ili drugi fotosenzibilizirajući lijek u posljednjih 6 mjeseci',
      'sl' => 'Roaccutane ali drugo fotosenzibilizirajoče zdravilo v zadnjih 6 mesecih',
      'et' => 'Roaccutane või muu valgustundlikkust põhjustav ravim viimase 6 kuu jooksul',
      'lv' => 'Roaccutane vai cits fotosensibilizējošs medikaments pēdējo 6 mēnešu laikā',
      'lt' => 'Roaccutane ar kitas fotosensibilizuojantis vaistas per pastaruosius 6 mėnesius',
    ),
    'enabled' => true,
  ),
  13 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'Tattooing is permanent and cannot be easily reversed.',
      'de' => 'Tätowieren ist dauerhaft und lässt sich nicht ohne Weiteres rückgängig machen.',
      'nl' => 'Een tatoeage is permanent en kan niet eenvoudig ongedaan worden gemaakt.',
      'fr' => 'Le tatouage est permanent et ne peut pas être facilement effacé.',
      'es' => 'El tatuaje es permanente y no se puede revertir fácilmente.',
      'it' => 'Il tatuaggio è permanente e non può essere facilmente rimosso.',
      'el' => 'Το τατουάζ είναι μόνιμο και δεν αναστρέφεται εύκολα.',
      'pt' => 'A tatuagem é permanente e não pode ser facilmente revertida.',
      'sv' => 'Att tatuera sig är permanent och kan inte enkelt göras ogjort.',
      'da' => 'Tatovering er permanent og kan ikke let fjernes igen.',
      'fi' => 'Tatuointi on pysyvä eikä sitä voi helposti peruuttaa.',
      'no' => 'Tatovering er permanent og kan ikke enkelt reverseres.',
      'pl' => 'Tatuaż jest trwały i nie można go łatwo usunąć.',
      'cs' => 'Tetování je trvalé a nelze jej snadno odstranit.',
      'sk' => 'Tetovanie je trvalé a nedá sa ľahko odstrániť.',
      'hu' => 'A tetoválás végleges, és nem lehet könnyen visszafordítani.',
      'ro' => 'Tatuajul este permanent și nu poate fi anulat cu ușurință.',
      'bg' => 'Татуировката е перманентна и не може лесно да бъде премахната.',
      'hr' => 'Tetoviranje je trajno i ne može se lako poništiti.',
      'sl' => 'Tetoviranje je trajno in ga ni mogoče enostavno odstraniti.',
      'et' => 'Tätoveerimine on püsiv ja seda ei saa lihtsalt tagasi pöörata.',
      'lv' => 'Tetovējums ir paliekošs, un to nevar viegli mainīt.',
      'lt' => 'Tatuiruotė yra ilgalaikė ir jos negalima lengvai pašalinti.',
    ),
    'enabled' => true,
  ),
  14 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'Results vary depending on skin type, tone, and healing.',
      'de' => 'Die Ergebnisse variieren je nach Hauttyp, Hautton und Heilungsverlauf.',
      'nl' => 'Resultaten variëren afhankelijk van huidtype, huidskleur en genezing.',
      'fr' => 'Les résultats varient selon le type de peau, le teint et la cicatrisation.',
      'es' => 'Los resultados varían según el tipo de piel, el tono y la cicatrización.',
      'it' => 'I risultati variano in base al tipo di pelle, alla tonalità e alla guarigione.',
      'el' => 'Το αποτέλεσμα ποικίλλει ανάλογα με τον τύπο δέρματος, την απόχρωση και την επούλωση.',
      'pt' => 'Os resultados variam consoante o tipo de pele, o tom e a cicatrização.',
      'sv' => 'Resultaten varierar beroende på hudtyp, hudton och läkning.',
      'da' => 'Resultaterne varierer afhængigt af hudtype, hudtone og helingsproces.',
      'fi' => 'Tulokset vaihtelevat ihotyypin, sävyn ja paranemisen mukaan.',
      'no' => 'Resultatene varierer avhengig av hudtype, hudtone og tilheling.',
      'pl' => 'Rezultaty różnią się w zależności od typu skóry, odcienia i procesu gojenia.',
      'cs' => 'Výsledky se liší podle typu pleti, tónu a hojení.',
      'sk' => 'Výsledky sa líšia podľa typu pleti, tónu a hojenia.',
      'hu' => 'Az eredmény a bőrtípustól, árnyalattól és gyógyulástól függően eltérő lehet.',
      'ro' => 'Rezultatele variază în funcție de tipul de piele, ton și vindecare.',
      'bg' => 'Резултатите варират в зависимост от типа кожа, тена и заздравяването.',
      'hr' => 'Rezultati variraju ovisno o tipu kože, tonu i cijeljenju.',
      'sl' => 'Rezultati se razlikujejo glede na tip kože, ton in celjenje.',
      'et' => 'Tulemused varieeruvad sõltuvalt nahatüübist, toonist ja paranemisest.',
      'lv' => 'Rezultāti atšķiras atkarībā no ādas veida, toņa un dzīšanas.',
      'lt' => 'Rezultatai skiriasi priklausomai nuo odos tipo, atspalvio ir gijimo.',
    ),
    'enabled' => true,
  ),
  15 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'There is a risk of infection, even with proper aftercare.',
      'de' => 'Es besteht ein Infektionsrisiko, auch bei richtiger Nachsorge.',
      'nl' => 'Er is een risico op infectie, zelfs bij goede nazorg.',
      'fr' => 'Il existe un risque d\'infection, même avec des soins post-tatouage adéquats.',
      'es' => 'Existe riesgo de infección, incluso con los cuidados posteriores adecuados.',
      'it' => 'Esiste un rischio di infezione, anche con una corretta cura post-tatuaggio.',
      'el' => 'Υπάρχει κίνδυνος μόλυνσης, ακόμη και με σωστή φροντίδα.',
      'pt' => 'Existe risco de infeção, mesmo com os cuidados pós-tatuagem adequados.',
      'sv' => 'Det finns en risk för infektion, även med korrekt efterbehandling.',
      'da' => 'Der er risiko for infektion, selv med korrekt efterbehandling.',
      'fi' => 'Infektioriski on olemassa, vaikka jälkihoito tehtäisiin oikein.',
      'no' => 'Det er en risiko for infeksjon, selv med riktig etterbehandling.',
      'pl' => 'Istnieje ryzyko infekcji, nawet przy prawidłowej pielęgnacji.',
      'cs' => 'Existuje riziko infekce, i při správné následné péči.',
      'sk' => 'Existuje riziko infekcie, aj pri správnej starostlivosti.',
      'hu' => 'Fennáll a fertőzés kockázata, még megfelelő utókezelés mellett is.',
      'ro' => 'Există un risc de infecție, chiar și cu îngrijire adecvată.',
      'bg' => 'Съществува риск от инфекция, дори при правилни грижи.',
      'hr' => 'Postoji rizik od infekcije, čak i uz pravilnu njegu.',
      'sl' => 'Obstaja tveganje za okužbo, tudi ob pravilni negi.',
      'et' => 'Nakkuse oht on olemas isegi õige järelhoolduse korral.',
      'lv' => 'Pastāv infekcijas risks pat pie pareizas aprūpes.',
      'lt' => 'Yra infekcijos rizika, net ir tinkamai prižiūrint.',
    ),
    'enabled' => true,
  ),
  16 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'Tattoo inks may cause an allergic reaction.',
      'de' => 'Tätowierfarben können allergische Reaktionen auslösen.',
      'nl' => 'Tatoeage-inkt kan een allergische reactie veroorzaken.',
      'fr' => 'Les encres de tatouage peuvent provoquer une réaction allergique.',
      'es' => 'Las tintas de tatuaje pueden causar una reacción alérgica.',
      'it' => 'Gli inchiostri per tatuaggi possono causare una reazione allergica.',
      'el' => 'Τα μελάνια τατουάζ μπορεί να προκαλέσουν αλλεργική αντίδραση.',
      'pt' => 'As tintas de tatuagem podem causar uma reação alérgica.',
      'sv' => 'Tatueringsbläck kan orsaka en allergisk reaktion.',
      'da' => 'Tatoveringsblæk kan forårsage en allergisk reaktion.',
      'fi' => 'Tatuointimuste voi aiheuttaa allergisen reaktion.',
      'no' => 'Tatoveringsblekk kan forårsake en allergisk reaksjon.',
      'pl' => 'Tusz do tatuażu może wywołać reakcję alergiczną.',
      'cs' => 'Tetovací inkoust může způsobit alergickou reakci.',
      'sk' => 'Tetovací atrament môže spôsobiť alergickú reakciu.',
      'hu' => 'A tetoválótinta allergiás reakciót válthat ki.',
      'ro' => 'Cernelurile de tatuaj pot provoca o reacție alergică.',
      'bg' => 'Мастилата за татуировка могат да причинят алергична реакция.',
      'hr' => 'Tinta za tetoviranje može izazvati alergijsku reakciju.',
      'sl' => 'Tetovažna tinta lahko povzroči alergijsko reakcijo.',
      'et' => 'Tätoveerimistint võib põhjustada allergilise reaktsiooni.',
      'lv' => 'Tetovējuma tinte var izraisīt alerģisku reakciju.',
      'lt' => 'Tatuiruotės rašalas gali sukelti alerginę reakciją.',
    ),
    'enabled' => true,
  ),
  17 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'Scarring or granulomas can occur.',
      'de' => 'Es können Narben oder Granulome entstehen.',
      'nl' => 'Er kunnen littekens of granulomen ontstaan.',
      'fr' => 'Des cicatrices ou des granulomes peuvent apparaître.',
      'es' => 'Pueden producirse cicatrices o granulomas.',
      'it' => 'Possono verificarsi cicatrici o granulomi.',
      'el' => 'Μπορεί να προκύψουν ουλές ή κοκκιώματα.',
      'pt' => 'Podem ocorrer cicatrizes ou granulomas.',
      'sv' => 'Ärr eller granulom kan uppstå.',
      'da' => 'Der kan opstå ar eller granulomer.',
      'fi' => 'Arpia tai granuloomia voi ilmaantua.',
      'no' => 'Arr eller granulomer kan oppstå.',
      'pl' => 'Mogą wystąpić blizny lub ziarniniaki.',
      'cs' => 'Mohou se objevit jizvy nebo granulomy.',
      'sk' => 'Môžu sa objaviť jazvy alebo granulómy.',
      'hu' => 'Hegek vagy granulómák alakulhatnak ki.',
      'ro' => 'Pot apărea cicatrici sau granuloame.',
      'bg' => 'Могат да се появят белези или granulomi.',
      'hr' => 'Mogu se pojaviti ožiljci ili granulomi.',
      'sl' => 'Lahko se pojavijo brazgotine ali granulomi.',
      'et' => 'Võivad tekkida armid või granuloomid.',
      'lv' => 'Var rasties rētas vai granulomas.',
      'lt' => 'Gali atsirasti randų ar granulomų.',
    ),
    'enabled' => true,
  ),
  18 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'Ink can spread beyond the intended line (blowout).',
      'de' => 'Farbe kann sich über die vorgesehene Linie hinaus ausbreiten (Blowout).',
      'nl' => 'Inkt kan zich verspreiden buiten de bedoelde lijn (blowout).',
      'fr' => 'L\'encre peut s\'étendre au-delà de la ligne prévue (bavure).',
      'es' => 'La tinta puede extenderse más allá de la línea prevista (blowout).',
      'it' => 'L\'inchiostro può diffondersi oltre la linea prevista (blowout).',
      'el' => 'Το μελάνι μπορεί να απλωθεί πέρα από την προβλεπόμενη γραμμή.',
      'pt' => 'A tinta pode espalhar-se além da linha prevista (blowout).',
      'sv' => 'Bläck kan spridas utanför den avsedda linjen (blowout).',
      'da' => 'Blæk kan sprede sig ud over den tilsigtede linje (blowout).',
      'fi' => 'Muste voi levitä suunnitellun linjan ulkopuolelle (blowout).',
      'no' => 'Blekk kan spre seg utenfor den tiltenkte linjen (blowout).',
      'pl' => 'Tusz może rozprzestrzenić się poza zamierzoną linię (rozmycie).',
      'cs' => 'Inkoust se může rozšířit za zamýšlenou linii (rozpití).',
      'sk' => 'Atrament sa môže rozšíriť za zamýšľanú líniu (rozpitie).',
      'hu' => 'A tinta a tervezett vonalon túl is szétterjedhet.',
      'ro' => 'Cerneala se poate extinde dincolo de linia dorită.',
      'bg' => 'Мастилото може да се разпростре извън предвидената линия.',
      'hr' => 'Tinta se može proširiti izvan predviđene linije.',
      'sl' => 'Tinta se lahko razširi izven predvidene linije.',
      'et' => 'Tint võib levida kavandatud joonest kaugemale.',
      'lv' => 'Tinte var izplesties ārpus paredzētās līnijas.',
      'lt' => 'Rašalas gali išplisti už numatytos linijos.',
    ),
    'enabled' => true,
  ),
  19 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'Tattoos fade over time and may need touch-ups.',
      'de' => 'Tattoos verblassen mit der Zeit und benötigen möglicherweise Auffrischungen.',
      'nl' => 'Tatoeages vervagen na verloop van tijd en kunnen bijwerkingen nodig hebben.',
      'fr' => 'Les tatouages s\'estompent avec le temps et peuvent nécessiter des retouches.',
      'es' => 'Los tatuajes se desvanecen con el tiempo y pueden necesitar retoques.',
      'it' => 'I tatuaggi sbiadiscono nel tempo e potrebbero richiedere ritocchi.',
      'el' => 'Τα τατουάζ ξεθωριάζουν με τον καιρό και μπορεί να χρειαστούν ρετούς.',
      'pt' => 'As tatuagens desvanecem com o tempo e podem precisar de retoques.',
      'sv' => 'Tatueringar bleknar med tiden och kan behöva retuscheras.',
      'da' => 'Tatoveringer falmer over tid og kan kræve efterbehandling.',
      'fi' => 'Tatuoinnit haalistuvat ajan myötä ja voivat tarvita viimeistelyä.',
      'no' => 'Tatoveringer falmer over tid og kan trenge retusjering.',
      'pl' => 'Tatuaże blakną z czasem i mogą wymagać poprawek.',
      'cs' => 'Tetování časem bledne a může vyžadovat dosycení.',
      'sk' => 'Tetovanie časom bledne a môže vyžadovať dofarbenie.',
      'hu' => 'A tetoválás idővel fakul, és javításra szorulhat.',
      'ro' => 'Tatuajele se estompează în timp și pot necesita retușuri.',
      'bg' => 'Татуировките избледняват с времето и може да се нуждаят от ретуш.',
      'hr' => 'Tetovaže blijede tijekom vremena i mogu zahtijevati dorade.',
      'sl' => 'Tetovaže sčasoma zbledijo in lahko potrebujejo popravke.',
      'et' => 'Tätoveeringud pleekivad aja jooksul ja võivad vajada värskendamist.',
      'lv' => 'Tetovējumi laika gaitā izbalē un var būt nepieciešama atjaunošana.',
      'lt' => 'Tatuiruotės laikui bėgant blunka ir gali reikėti korekcijos.',
    ),
    'enabled' => true,
  ),
  20 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'The final result may not exactly match a reference image.',
      'de' => 'Das Endergebnis stimmt möglicherweise nicht genau mit einem Referenzbild überein.',
      'nl' => 'Het eindresultaat komt mogelijk niet exact overeen met een referentieafbeelding.',
      'fr' => 'Le résultat final peut ne pas correspondre exactement à une image de référence.',
      'es' => 'El resultado final puede no coincidir exactamente con una imagen de referencia.',
      'it' => 'Il risultato finale potrebbe non corrispondere esattamente a un\'immagine di riferimento.',
      'el' => 'Το τελικό αποτέλεσμα μπορεί να μην ταιριάζει ακριβώς με μια εικόνα αναφοράς.',
      'pt' => 'O resultado final pode não corresponder exatamente a uma imagem de referência.',
      'sv' => 'Slutresultatet kanske inte exakt matchar en referensbild.',
      'da' => 'Det endelige resultat matcher muligvis ikke nøjagtigt et referencebillede.',
      'fi' => 'Lopullinen tulos ei välttämättä vastaa täysin viitekuvaa.',
      'no' => 'Sluttresultatet samsvarer kanskje ikke nøyaktig med et referansebilde.',
      'pl' => 'Ostateczny efekt może nie odpowiadać dokładnie obrazowi referencyjnemu.',
      'cs' => 'Konečný výsledek nemusí přesně odpovídat referenčnímu obrázku.',
      'sk' => 'Konečný výsledok nemusí presne zodpovedať referenčnému obrázku.',
      'hu' => 'A végeredmény nem feltétlenül egyezik pontosan a referenciaképpel.',
      'ro' => 'Rezultatul final poate să nu corespundă exact imaginii de referință.',
      'bg' => 'Крайният резултат може да не съвпада точно с референтното изображение.',
      'hr' => 'Konačni rezultat možda neće u potpunosti odgovarati referentnoj slici.',
      'sl' => 'Končni rezultat morda ne bo natančno ustrezal referenčni sliki.',
      'et' => 'Lõpptulemus ei pruugi täpselt vastata viitepildile.',
      'lv' => 'Galīgais rezultāts var precīzi neatbilst atsauces attēlam.',
      'lt' => 'Galutinis rezultatas gali tiksliai neatitikti pavyzdinio paveikslėlio.',
    ),
    'enabled' => true,
  ),
  21 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'Healing outcome depends significantly on aftercare.',
      'de' => 'Der Heilungsverlauf hängt maßgeblich von der Nachsorge ab.',
      'nl' => 'Het genezingsresultaat hangt sterk af van de nazorg.',
      'fr' => 'Le résultat de la cicatrisation dépend largement des soins post-tatouage.',
      'es' => 'El resultado de la cicatrización depende en gran medida de los cuidados posteriores.',
      'it' => 'L\'esito della guarigione dipende in gran parte dalla cura post-tatuaggio.',
      'el' => 'Το αποτέλεσμα της επούλωσης εξαρτάται σημαντικά από τη φροντίδα.',
      'pt' => 'O resultado da cicatrização depende significativamente dos cuidados pós-tatuagem.',
      'sv' => 'Läkningsresultatet beror till stor del på efterbehandlingen.',
      'da' => 'Helingsresultatet afhænger i høj grad af efterbehandlingen.',
      'fi' => 'Paranemistulos riippuu merkittävästi jälkihoidosta.',
      'no' => 'Tilhelingsresultatet avhenger i stor grad av etterbehandlingen.',
      'pl' => 'Wynik gojenia w dużym stopniu zależy od pielęgnacji.',
      'cs' => 'Výsledek hojení výrazně závisí na následné péči.',
      'sk' => 'Výsledok hojenia výrazne závisí od starostlivosti.',
      'hu' => 'A gyógyulás kimenetele nagymértékben az utókezeléstől függ.',
      'ro' => 'Rezultatul vindecării depinde semnificativ de îngrijirea ulterioară.',
      'bg' => 'Резултатът от заздравяването зависи значително от грижите.',
      'hr' => 'Ishod cijeljenja u velikoj mjeri ovisi o njezi.',
      'sl' => 'Izid celjenja je v veliki meri odvisen od nege.',
      'et' => 'Paranemistulemus sõltub oluliselt järelhooldusest.',
      'lv' => 'Dzīšanas rezultāts lielā mērā ir atkarīgs no aprūpes.',
      'lt' => 'Gijimo rezultatas labai priklauso nuo priežiūros.',
    ),
    'enabled' => true,
  ),
  22 => 
  array (
    'question_type' => 'risk',
    'translations' => 
    array (
      'en' => 'I confirm I am not under the influence of alcohol or drugs.',
      'de' => 'Ich bestätige, dass ich nicht unter dem Einfluss von Alkohol oder Drogen stehe.',
      'nl' => 'Ik bevestig dat ik niet onder invloed ben van alcohol of drugs.',
      'fr' => 'Je confirme ne pas être sous l\'influence de l\'alcool ou de drogues.',
      'es' => 'Confirmo que no estoy bajo los efectos del alcohol o las drogas.',
      'it' => 'Confermo di non essere sotto l\'effetto di alcol o droghe.',
      'el' => 'Επιβεβαιώνω ότι δεν βρίσκομαι υπό την επήρεια αλκοόλ ή ουσιών.',
      'pt' => 'Confirmo que não estou sob o efeito de álcool ou drogas.',
      'sv' => 'Jag bekräftar att jag inte är påverkad av alkohol eller droger.',
      'da' => 'Jeg bekræfter, at jeg ikke er påvirket af alkohol eller stoffer.',
      'fi' => 'Vahvistan, etten ole alkoholin tai huumeiden vaikutuksen alainen.',
      'no' => 'Jeg bekrefter at jeg ikke er påvirket av alkohol eller rusmidler.',
      'pl' => 'Potwierdzam, że nie jestem pod wpływem alkoholu ani narkotyków.',
      'cs' => 'Potvrzuji, že nejsem pod vlivem alkoholu ani drog.',
      'sk' => 'Potvrdzujem, že nie som pod vplyvom alkoholu ani drog.',
      'hu' => 'Megerősítem, hogy nem állok alkohol vagy drogok hatása alatt.',
      'ro' => 'Confirm că nu mă aflu sub influența alcoolului sau a drogurilor.',
      'bg' => 'Потвърждавам, че не съм под влияние на алкохол или наркотици.',
      'hr' => 'Potvrđujem da nisam pod utjecajem alkohola ili droga.',
      'sl' => 'Potrjujem, da nisem pod vplivom alkohola ali drog.',
      'et' => 'Kinnitan, et ei ole alkoholi ega narkootikumide mõju all.',
      'lv' => 'Es apstiprinu, ka neesmu alkohola vai narkotiku ietekmē.',
      'lt' => 'Patvirtinu, kad nesu apsvaigęs nuo alkoholio ar narkotikų.',
    ),
    'enabled' => true,
  ),
  23 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Keep the wrap on for 2 hours after your session.',
      'de' => 'Lassen Sie die Folie 2 Stunden nach der Sitzung drauf.',
      'nl' => 'Houd de wikkel 2 uur na de sessie op.',
      'fr' => 'Gardez le film pendant 2 heures après votre séance.',
      'es' => 'Mantenga el vendaje durante 2 horas después de la sesión.',
      'it' => 'Tenere la pellicola per 2 ore dopo la seduta.',
      'el' => 'Κρατήστε την επίδεση για 2 ώρες μετά τη συνεδρία.',
      'pt' => 'Mantenha o penso durante 2 horas após a sessão.',
      'sv' => 'Ha omslaget kvar i 2 timmar efter din session.',
      'da' => 'Behold forbindingen på i 2 timer efter din session.',
      'fi' => 'Pidä suoja 2 tuntia istunnon jälkeen.',
      'no' => 'Ha bandasjen på i 2 timer etter økten.',
      'pl' => 'Pozostaw opatrunek na 2 godziny po sesji.',
      'cs' => 'Nechte fólii 2 hodiny po sezení.',
      'sk' => 'Nechajte fóliu 2 hodiny po sedení.',
      'hu' => 'Hagyja a fóliát 2 órán át a kezelés után.',
      'ro' => 'Păstrați folia timp de 2 ore după ședință.',
      'bg' => 'Оставете превръзката за 2 часа след сеанса.',
      'hr' => 'Zadržite omot 2 sata nakon seanse.',
      'sl' => 'Povoj pustite 2 uri po seansi.',
      'et' => 'Hoidke kilet peal 2 tundi pärast seanssi.',
      'lv' => 'Atstājiet apsēju 2 stundas pēc seansa.',
      'lt' => 'Palikite tvarstį 2 valandas po seanso.',
    ),
    'enabled' => true,
  ),
  24 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Wash gently with fragrance-free, dye-free soap and clean hands.',
      'de' => 'Sanft mit parfüm- und farbstofffreier Seife und sauberen Händen waschen.',
      'nl' => 'Was voorzichtig met geurloze, kleurstofvrije zeep en schone handen.',
      'fr' => 'Lavez délicatement avec un savon sans parfum ni colorant et des mains propres.',
      'es' => 'Lave suavemente con jabón sin fragancia ni tinte y manos limpias.',
      'it' => 'Lavare delicatamente con sapone senza profumo né coloranti e mani pulite.',
      'el' => 'Πλύνετε απαλά με άρωμα-ελεύθερο σαπούνι και καθαρά χέρια.',
      'pt' => 'Lave suavemente com sabão sem fragrância nem corante e mãos limpas.',
      'sv' => 'Tvätta försiktigt med doft- och färgfri tvål och rena händer.',
      'da' => 'Vask forsigtigt med parfume- og farvefri sæbe og rene hænder.',
      'fi' => 'Pese varovasti hajusteettomalla, väriaineettomalla saippualla ja puhtailla käsillä.',
      'no' => 'Vask forsiktig med parfyme- og fargefri såpe og rene hender.',
      'pl' => 'Myj delikatnie bezzapachowym mydłem bez barwników, czystymi rękami.',
      'cs' => 'Jemně omývejte mýdlem bez parfemace a barviv čistýma rukama.',
      'sk' => 'Jemne umývajte mydlom bez parfumácie a farbív čistými rukami.',
      'hu' => 'Mossa óvatosan illat- és festékmentes szappannal, tiszta kézzel.',
      'ro' => 'Spălați ușor cu săpun fără parfum și coloranți și mâini curate.',
      'bg' => 'Мийте внимателно с сапун без аромат и оцветители и чисти ръце.',
      'hr' => 'Nježno perite sapunom bez mirisa i boja te čistim rukama.',
      'sl' => 'Nežno umivajte z milom brez vonja in barvil ter čistimi rokami.',
      'et' => 'Peske õrnalt lõhna- ja värvainevaba seebiga ning puhaste kätega.',
      'lv' => 'Maigi mazgājiet ar smaržvielu un krāsvielu nesaturošu ziepēm un tīrām rokām.',
      'lt' => 'Švelniai plaukite bekvapiu, be dažų muilu švariomis rankomis.',
    ),
    'enabled' => true,
  ),
  25 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Pat dry with a clean paper towel — don\'t rub.',
      'de' => 'Mit einem sauberen Papiertuch trockentupfen – nicht reiben.',
      'nl' => 'Deppen met een schone papieren handdoek — niet wrijven.',
      'fr' => 'Tamponnez avec une serviette en papier propre, ne frottez pas.',
      'es' => 'Seque con toques suaves con una toalla de papel limpia, sin frotar.',
      'it' => 'Tamponare con un asciugamano di carta pulito, senza strofinare.',
      'el' => 'Στεγνώστε με καθαρό χαρτί κουζίνας — μην τρίβετε.',
      'pt' => 'Seque com toques com uma toalha de papel limpa — não esfregue.',
      'sv' => 'Klappa torrt med en ren pappershandduk — gnid inte.',
      'da' => 'Dup tør med et rent stykke køkkenrulle — undgå at gnide.',
      'fi' => 'Taputtele kuivaksi puhtaalla paperipyyhkeellä — älä hankaa.',
      'no' => 'Dupp tørr med et rent papirhåndkle — ikke gni.',
      'pl' => 'Osusz delikatnie czystym ręcznikiem papierowym — nie pocieraj.',
      'cs' => 'Jemně osušte čistým papírovým ubrouskem — netřete.',
      'sk' => 'Jemne osušte čistou papierovou utierkou — nepotierajte.',
      'hu' => 'Óvatosan itassa fel tiszta papírtörlővel — ne dörzsölje.',
      'ro' => 'Tamponați cu un prosop de hârtie curat — nu frecați.',
      'bg' => 'Подсушете внимателно с чиста хартиена кърпа — не търкайте.',
      'hr' => 'Nježno osušite čistim papirnatim ručnikom — ne trljajte.',
      'sl' => 'Nežno posušite s čisto papirnato brisačo — ne drgnite.',
      'et' => 'Tupsutage kuivaks puhta paberrätikuga — ärge hõõruge.',
      'lv' => 'Nosusiniet ar tīru papīra dvieli — neberzējiet.',
      'lt' => 'Nusausinkite švariu popieriniu rankšluosčiu — netrinkite.',
    ),
    'enabled' => true,
  ),
  26 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Apply a thin layer of the recommended moisturiser.',
      'de' => 'Eine dünne Schicht der empfohlenen Feuchtigkeitscreme auftragen.',
      'nl' => 'Breng een dun laagje van de aanbevolen hydraterende crème aan.',
      'fr' => 'Appliquez une fine couche de la crème hydratante recommandée.',
      'es' => 'Aplique una capa fina de la crema hidratante recomendada.',
      'it' => 'Applicare un sottile strato della crema idratante consigliata.',
      'el' => 'Απλώστε λεπτό στρώμα από την προτεινόμενη ενυδατική κρέμα.',
      'pt' => 'Aplique uma camada fina do hidratante recomendado.',
      'sv' => 'Applicera ett tunt lager av den rekommenderade fuktkrämen.',
      'da' => 'Påfør et tyndt lag af den anbefalede fugtighedscreme.',
      'fi' => 'Levitä ohut kerros suositeltua kosteusvoidetta.',
      'no' => 'Påfør et tynt lag med den anbefalte fuktighetskremen.',
      'pl' => 'Nałóż cienką warstwę zalecanego kremu nawilżającego.',
      'cs' => 'Naneste tenkou vrstvu doporučeného hydratačního krému.',
      'sk' => 'Naneste tenkú vrstvu odporúčaného hydratačného krému.',
      'hu' => 'Vigyen fel vékony réteg ajánlott hidratáló krémet.',
      'ro' => 'Aplicați un strat subțire din crema hidratantă recomandată.',
      'bg' => 'Нанесете тънък слой от препоръчания овлажнител.',
      'hr' => 'Nanesite tanak sloj preporučene hidratantne kreme.',
      'sl' => 'Nanesite tanko plast priporočene vlažilne kreme.',
      'et' => 'Kandke peale õhuke kiht soovitatud niisutuskreemi.',
      'lv' => 'Uzklājiet plānu ieteiktā mitrinošā krēma kārtu.',
      'lt' => 'Užtepkite ploną rekomenduojamo drėkinamojo kremo sluoksnį.',
    ),
    'enabled' => true,
  ),
  27 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Repeat washing and moisturising 2–3 times daily until fully healed.',
      'de' => 'Waschen und Eincremen 2–3 Mal täglich wiederholen, bis die Wunde vollständig verheilt ist.',
      'nl' => 'Herhaal wassen en hydrateren 2–3 keer per dag tot volledig genezen.',
      'fr' => 'Répétez le lavage et l\'hydratation 2 à 3 fois par jour jusqu\'à guérison complète.',
      'es' => 'Repita el lavado e hidratación 2–3 veces al día hasta la curación completa.',
      'it' => 'Ripetere il lavaggio e l\'idratazione 2–3 volte al giorno fino alla completa guarigione.',
      'el' => 'Επαναλάβετε το πλύσιμο και την ενυδάτωση 2–3 φορές την ημέρα μέχρι πλήρη επούλωση.',
      'pt' => 'Repita a lavagem e hidratação 2–3 vezes por dia até à cicatrização completa.',
      'sv' => 'Upprepa tvätt och fuktgivning 2–3 gånger dagligen tills det är helt läkt.',
      'da' => 'Gentag vask og fugtgivning 2–3 gange dagligt, indtil det er helt helet.',
      'fi' => 'Toista pesu ja kosteutus 2–3 kertaa päivässä, kunnes täysin parantunut.',
      'no' => 'Gjenta vask og fukting 2–3 ganger daglig til det er helt tilhelet.',
      'pl' => 'Powtarzaj mycie i nawilżanie 2–3 razy dziennie aż do pełnego zagojenia.',
      'cs' => 'Opakujte omývání a hydrataci 2–3krát denně až do úplného zhojení.',
      'sk' => 'Opakujte umývanie a hydratáciu 2–3-krát denne, kým sa úplne nezahojí.',
      'hu' => 'Ismételje a mosást és hidratálást naponta 2–3 alkalommal a teljes gyógyulásig.',
      'ro' => 'Repetați spălarea și hidratarea de 2–3 ori pe zi până la vindecarea completă.',
      'bg' => 'Повтаряйте измиването и овлажняването 2–3 пъти дневно до пълно заздравяване.',
      'hr' => 'Ponavljajte pranje i hidrataciju 2–3 puta dnevno do potpunog zacjeljivanja.',
      'sl' => 'Ponavljajte umivanje in vlaženje 2–3-krat dnevno do popolne zacelitve.',
      'et' => 'Korrake pesemist ja niisutamist 2–3 korda päevas kuni täieliku paranemiseni.',
      'lv' => 'Atkārtojiet mazgāšanu un mitrināšanu 2–3 reizes dienā, līdz brūce pilnībā sadzīst.',
      'lt' => 'Kartokite plovimą ir drėkinimą 2–3 kartus per dieną, kol visiškai užgis.',
    ),
    'enabled' => true,
  ),
  28 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Avoid direct sun exposure on the healing tattoo.',
      'de' => 'Direkte Sonneneinstrahlung auf das heilende Tattoo vermeiden.',
      'nl' => 'Vermijd directe zonlicht op de genezende tatoeage.',
      'fr' => 'Évitez l\'exposition directe au soleil sur le tatouage en cicatrisation.',
      'es' => 'Evite la exposición directa al sol en el tatuaje en cicatrización.',
      'it' => 'Evitare l\'esposizione diretta al sole sul tatuaggio in guarigione.',
      'el' => 'Αποφύγετε την έκθεση στον ήλιο όσο επουλώνεται το τατουάζ.',
      'pt' => 'Evite a exposição direta ao sol na tatuagem em cicatrização.',
      'sv' => 'Undvik direkt solljus på tatueringen medan den läker.',
      'da' => 'Undgå direkte sollys på den helende tatovering.',
      'fi' => 'Vältä suoraa auringonvaloa parantuvassa tatuoinnissa.',
      'no' => 'Unngå direkte sollys på tatoveringen mens den gror.',
      'pl' => 'Unikaj bezpośredniego działania słońca na gojący się tatuaż.',
      'cs' => 'Vyhněte se přímému slunečnímu záření na hojící se tetování.',
      'sk' => 'Vyhýbajte sa priamemu slnečnému žiareniu na hojace sa tetovanie.',
      'hu' => 'Kerülje a közvetlen napfényt a gyógyuló tetováláson.',
      'ro' => 'Evitați expunerea directă la soare a tatuajului în curs de vindecare.',
      'bg' => 'Избягвайте директна слънчева светлина върху зарастващата татуировка.',
      'hr' => 'Izbjegavajte izravno sunčevo svjetlo na tetovaži koja cijeli.',
      'sl' => 'Izogibajte se neposredni sončni svetlobi na celeči se tetovaži.',
      'et' => 'Vältige otsest päikesevalgust paraneval tätoveeringul.',
      'lv' => 'Izvairieties no tiešiem saules stariem uz dzīstoša tetovējuma.',
      'lt' => 'Venkite tiesioginių saulės spindulių ant gyjančios tatuiruotės.',
    ),
    'enabled' => true,
  ),
  29 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Don\'t submerge in pools, hot tubs, or open water until fully healed.',
      'de' => 'Nicht in Pools, Whirlpools oder offenem Wasser baden, bis vollständig verheilt.',
      'nl' => 'Niet onderdompelen in zwembaden, hot tubs of open water tot volledig genezen.',
      'fr' => 'Ne plongez pas dans une piscine, un spa ou de l\'eau libre avant guérison complète.',
      'es' => 'No se sumerja en piscinas, jacuzzis o agua abierta hasta la curación completa.',
      'it' => 'Non immergersi in piscine, vasche idromassaggio o acque libere fino alla guarigione completa.',
      'el' => 'Μην βυθίζεστε σε πισίνες, τζακούζι ή ανοιχτά νερά μέχρι πλήρη επούλωση.',
      'pt' => 'Não mergulhe em piscinas, jacuzzis ou águas abertas até à cicatrização completa.',
      'sv' => 'Undvik att bada i pooler, jacuzzier eller öppet vatten tills det är helt läkt.',
      'da' => 'Undgå at dykke ned i pools, spabade eller åbent vand, indtil det er helt helet.',
      'fi' => 'Älä upota uima-altaisiin, poreammeisiin tai avoveteen ennen täydellistä paranemista.',
      'no' => 'Ikke dypp i basseng, boblebad eller åpent vann før det er helt tilhelet.',
      'pl' => 'Nie zanurzaj się w basenach, jacuzzi ani otwartej wodzie aż do pełnego zagojenia.',
      'cs' => 'Neponořujte se do bazénů, vířivek ani otevřené vody až do úplného zhojení.',
      'sk' => 'Neponárajte sa do bazénov, vírivky ani otvorenej vody, kým sa úplne nezahojí.',
      'hu' => 'Ne merüljön medencébe, jakuzziba vagy nyílt vízbe teljes gyógyulásig.',
      'ro' => 'Nu vă scufundați în piscine, jacuzzi sau ape deschise până la vindecarea completă.',
      'bg' => 'Не се потапяйте в басейни, джакузита или открити води до пълно заздравяване.',
      'hr' => 'Ne uranjajte u bazene, jacuzzije ili otvorenu vodu do potpunog zacjeljivanja.',
      'sl' => 'Ne potapljajte se v bazene, vrtinčne kadi ali odprto vodo do popolne zacelitve.',
      'et' => 'Ärge sukelduge basseinidesse, mullivannidesse ega avaveekogudesse enne täielikku paranemist.',
      'lv' => 'Neiegremdējieties baseinos, džakuzi vai atklātā ūdenī, līdz brūce pilnībā sadzīst.',
      'lt' => 'Nesineriminkite į baseinus, spa vonias ar atvirus vandenis, kol visiškai užgis.',
    ),
    'enabled' => true,
  ),
  30 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Don\'t scratch, pick, or peel flaking skin.',
      'de' => 'Abblätternde Haut nicht kratzen, pulen oder abziehen.',
      'nl' => 'Krab, peuter of pel niet aan vervellende huid.',
      'fr' => 'Ne grattez pas, ne tirez pas et ne pelez pas la peau qui pèle.',
      'es' => 'No rasque, pellizque ni pele la piel que se descama.',
      'it' => 'Non grattare, staccare o sbucciare la pelle che si desquama.',
      'el' => 'Μην ξύνετε ή αφαιρείτε το δέρμα που ξεφλουδίζει.',
      'pt' => 'Não coce, arranque ou descasque a pele que está a esfoliar.',
      'sv' => 'Klia, plocka eller pilla inte på fjällande hud.',
      'da' => 'Undgå at kradse, pille eller flå hud, der skaller af.',
      'fi' => 'Älä raavi, näpertele tai kuori hilseilevää ihoa.',
      'no' => 'Ikke klø, plukk eller flerr av flassende hud.',
      'pl' => 'Nie drap, nie odrywaj ani nie łuszcz łuszczącej się skóry.',
      'cs' => 'Neškrábejte, netrhejte ani neloupejte odlupující se kůži.',
      'sk' => 'Neškriabte, netrhajte ani neošúpavajte olupujúcu sa kožu.',
      'hu' => 'Ne vakarja, ne piszkálja és ne húzza le a hámló bőrt.',
      'ro' => 'Nu zgâriați, nu ciupiți și nu jupuiți pielea care se cojește.',
      'bg' => 'Не се чешете, не откъсвайте и не белете лющещата се кожа.',
      'hr' => 'Ne grebite, ne čupkajte i ne guljajte kožu koja se ljušti.',
      'sl' => 'Ne praskajte, ne trgajte in ne lupite luščeče se kože.',
      'et' => 'Ärge kraapige, näpistage ega koorige ketendavat nahka.',
      'lv' => 'Nekasieties, neplūciet un nelobiet lobošos ādu.',
      'lt' => 'Neplėškite, negremžkite ir nelupkite šeriamos odos.',
    ),
    'enabled' => true,
  ),
  31 => 
  array (
    'question_type' => 'aftercare',
    'translations' => 
    array (
      'en' => 'Avoid tight clothing over the tattoo site during healing.',
      'de' => 'Enge Kleidung über der Tattoo-Stelle während der Heilung vermeiden.',
      'nl' => 'Vermijd strakke kleding over de tatoeageplek tijdens het genezen.',
      'fr' => 'Évitez les vêtements serrés sur la zone tatouée pendant la cicatrisation.',
      'es' => 'Evite ropa ajustada sobre el área del tatuaje durante la cicatrización.',
      'it' => 'Evitare indumenti aderenti sulla zona del tatuaggio durante la guarigione.',
      'el' => 'Αποφύγετε τα στενά ρούχα πάνω από την περιοχή του τατουάζ κατά την επούλωση.',
      'pt' => 'Evite roupas apertadas sobre a zona da tatuagem durante a cicatrização.',
      'sv' => 'Undvik åtsittande kläder över tatueringen under läkningen.',
      'da' => 'Undgå stramt tøj over tatoveringsstedet under helingen.',
      'fi' => 'Vältä tiukkoja vaatteita tatuointikohdan päällä paranemisen aikana.',
      'no' => 'Unngå stramme klær over tatoveringsstedet under tilhelingen.',
      'pl' => 'Unikaj ciasnej odzieży w miejscu tatuażu podczas gojenia.',
      'cs' => 'Vyhněte se těsnému oblečení přes místo tetování během hojení.',
      'sk' => 'Vyhýbajte sa tesnému oblečeniu na mieste tetovania počas hojenia.',
      'hu' => 'Kerülje a szoros ruházatot a tetoválás helyén a gyógyulás alatt.',
      'ro' => 'Evitați hainele strâmte peste zona tatuajului în timpul vindecării.',
      'bg' => 'Избягвайте тесни дрехи върху мястото на татуировката по време на заздравяване.',
      'hr' => 'Izbjegavajte tijesnu odjeću preko mjesta tetovaže tijekom cijeljenja.',
      'sl' => 'Izogibajte se tesnim oblačilom čez mesto tetovaže med celjenjem.',
      'et' => 'Vältige kitsaid riideid tätoveeringu koha peal paranemise ajal.',
      'lv' => 'Izvairieties no cieša apģērba virs tetovējuma vietas dzīšanas laikā.',
      'lt' => 'Venkite ankštų drabužių ant tatuiruotės vietos gijimo metu.',
    ),
    'enabled' => true,
  ),
);

        foreach ($questions as $question) {
            ConsentFormQuestion::query()->create([
                'user_id' => $userId,
                'question_type' => $question['question_type'],
                'translations' => $question['translations'],
                'enabled' => $question['enabled'],
            ]);
        }
    }
}
