<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InkjinTattooSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get artist handles
        $artists = DB::table('inkjin_artists')->pluck('artist_handle')->toArray();
        
        if (empty($artists)) {
            $this->command->error('No artists found. Please run InkjinArtistSeeder first.');
            return;
        }

        $tattoos = [];

        // Tattoos for first artist (inkmaster_alex)
        $tattoos = array_merge($tattoos, [
            [
                'artist_handle' => $artists[0],
                'type' => 'realism',
                'visibility' => 'public',
                'filename' => 'realistic_portrait_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'no',
                'sensitive' => 'no',
                'title' => 'Realistic Portrait Tattoo',
                'description' => 'A stunning realistic portrait tattoo showcasing incredible detail and shading techniques.',
                'primary_style' => 'Realism',
                'other_styles' => 'Portrait, Black and Grey',
                'suggested_placement' => 'Forearm',
                'color' => 'Black and Grey',
                'tags' => 'portrait, realism, black and grey, detailed',
                'price' => '800',
                'max_price' => '1200',
                'size_height' => '6',
                'size_width' => '4',
                'cost_per_session' => '400',
                'min_sessions' => '2',
                'max_sessions' => '3',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Requires consultation before booking. High detail work.',
            ],
            [
                'artist_handle' => $artists[0],
                'type' => 'realism',
                'visibility' => 'public',
                'filename' => 'wildlife_realism_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Wildlife Realism Tattoo',
                'description' => 'Beautiful wildlife realism tattoo featuring a majestic eagle with incredible detail.',
                'primary_style' => 'Realism',
                'other_styles' => 'Wildlife, Nature',
                'suggested_placement' => 'Back',
                'color' => 'Color',
                'tags' => 'wildlife, eagle, realism, color, nature',
                'price' => '1500',
                'max_price' => '2000',
                'size_height' => '10',
                'size_width' => '8',
                'cost_per_session' => '500',
                'min_sessions' => '3',
                'max_sessions' => '4',
                'session_time_h' => '5',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Large piece, multiple sessions required.',
            ],
            [
                'artist_handle' => $artists[0],
                'type' => 'portrait',
                'visibility' => 'public',
                'filename' => 'portrait_memorial_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'no',
                'sensitive' => 'no',
                'title' => 'Memorial Portrait',
                'description' => 'Emotional memorial portrait tattoo with exceptional detail and shading.',
                'primary_style' => 'Realism',
                'other_styles' => 'Portrait, Memorial',
                'suggested_placement' => 'Chest',
                'color' => 'Black and Grey',
                'tags' => 'portrait, memorial, realism, emotional',
                'price' => '1000',
                'max_price' => '1500',
                'size_height' => '5',
                'size_width' => '4',
                'cost_per_session' => '500',
                'min_sessions' => '2',
                'max_sessions' => '3',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Please bring reference photos for consultation.',
            ],
            [
                'artist_handle' => $artists[0],
                'type' => 'realism',
                'visibility' => 'public',
                'filename' => 'flower_realism_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Realistic Rose Tattoo',
                'description' => 'Stunning realistic rose tattoo with incredible detail and depth.',
                'primary_style' => 'Realism',
                'other_styles' => 'Floral, Nature',
                'suggested_placement' => 'Shoulder',
                'color' => 'Color',
                'tags' => 'rose, flower, realism, color, floral',
                'price' => '600',
                'max_price' => '900',
                'size_height' => '4',
                'size_width' => '3',
                'cost_per_session' => '300',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Popular design, can be customized.',
            ],
            [
                'artist_handle' => $artists[0],
                'type' => 'realism',
                'visibility' => 'public',
                'filename' => 'animal_portrait_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Pet Portrait Realism',
                'description' => 'Lifelike pet portrait tattoo capturing every detail of your beloved companion.',
                'primary_style' => 'Realism',
                'other_styles' => 'Portrait, Pet',
                'suggested_placement' => 'Forearm',
                'color' => 'Black and Grey',
                'tags' => 'pet, portrait, realism, dog, cat',
                'price' => '700',
                'max_price' => '1000',
                'size_height' => '5',
                'size_width' => '4',
                'cost_per_session' => '350',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'High quality reference photos required.',
            ],
        ]);

        // Tattoos for second artist (tattoo_sarah)
        $tattoos = array_merge($tattoos, [
            [
                'artist_handle' => $artists[1],
                'type' => 'watercolor',
                'visibility' => 'public',
                'filename' => 'watercolor_abstract_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Watercolor Abstract Design',
                'description' => 'Beautiful watercolor abstract tattoo with flowing colors and artistic expression.',
                'primary_style' => 'Watercolor',
                'other_styles' => 'Abstract, Color',
                'suggested_placement' => 'Thigh',
                'color' => 'Color',
                'tags' => 'watercolor, abstract, color, artistic',
                'price' => '500',
                'max_price' => '800',
                'size_height' => '6',
                'size_width' => '5',
                'cost_per_session' => '400',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Unique design, each piece is one-of-a-kind.',
            ],
            [
                'artist_handle' => $artists[1],
                'type' => 'floral',
                'visibility' => 'public',
                'filename' => 'watercolor_floral_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Watercolor Floral Bouquet',
                'description' => 'Stunning watercolor floral tattoo with vibrant colors and artistic flow.',
                'primary_style' => 'Watercolor',
                'other_styles' => 'Floral, Color',
                'suggested_placement' => 'Rib',
                'color' => 'Color',
                'tags' => 'watercolor, floral, flowers, color, feminine',
                'price' => '600',
                'max_price' => '900',
                'size_height' => '8',
                'size_width' => '4',
                'cost_per_session' => '450',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Can be customized with favorite flowers.',
            ],
            [
                'artist_handle' => $artists[1],
                'type' => 'geometric',
                'visibility' => 'public',
                'filename' => 'geometric_watercolor_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Geometric Watercolor Mandala',
                'description' => 'Unique geometric mandala with watercolor accents and precise linework.',
                'primary_style' => 'Watercolor',
                'other_styles' => 'Geometric, Mandala',
                'suggested_placement' => 'Back',
                'color' => 'Color',
                'tags' => 'geometric, mandala, watercolor, color, spiritual',
                'price' => '800',
                'max_price' => '1200',
                'size_height' => '7',
                'size_width' => '7',
                'cost_per_session' => '400',
                'min_sessions' => '2',
                'max_sessions' => '3',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Complex design requires multiple sessions.',
            ],
            [
                'artist_handle' => $artists[1],
                'type' => 'abstract',
                'visibility' => 'public',
                'filename' => 'abstract_flow_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Abstract Flow Design',
                'description' => 'Flowing abstract design with watercolor technique and artistic expression.',
                'primary_style' => 'Watercolor',
                'other_styles' => 'Abstract, Color',
                'suggested_placement' => 'Arm',
                'color' => 'Color',
                'tags' => 'abstract, watercolor, flow, color, artistic',
                'price' => '450',
                'max_price' => '700',
                'size_height' => '5',
                'size_width' => '3',
                'cost_per_session' => '350',
                'min_sessions' => '1',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Each design is unique and custom.',
            ],
            [
                'artist_handle' => $artists[1],
                'type' => 'floral',
                'visibility' => 'public',
                'filename' => 'delicate_floral_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Delicate Watercolor Flowers',
                'description' => 'Delicate and feminine watercolor floral design with soft colors.',
                'primary_style' => 'Watercolor',
                'other_styles' => 'Floral, Fine Line',
                'suggested_placement' => 'Ankle',
                'color' => 'Color',
                'tags' => 'floral, watercolor, delicate, feminine, color',
                'price' => '350',
                'max_price' => '550',
                'size_height' => '3',
                'size_width' => '2',
                'cost_per_session' => '300',
                'min_sessions' => '1',
                'max_sessions' => '2',
                'session_time_h' => '2',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Perfect for first tattoo or small piece.',
            ],
        ]);

        // Tattoos for third artist (dark_ink_mike)
        $tattoos = array_merge($tattoos, [
            [
                'artist_handle' => $artists[2],
                'type' => 'traditional',
                'visibility' => 'public',
                'filename' => 'american_traditional_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Classic American Traditional Eagle',
                'description' => 'Bold American traditional eagle tattoo with classic bold lines and vibrant colors.',
                'primary_style' => 'Traditional',
                'other_styles' => 'American Traditional',
                'suggested_placement' => 'Chest',
                'color' => 'Color',
                'tags' => 'traditional, eagle, american, bold, classic',
                'price' => '600',
                'max_price' => '800',
                'size_height' => '8',
                'size_width' => '6',
                'cost_per_session' => '400',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Classic design, timeless style.',
            ],
            [
                'artist_handle' => $artists[2],
                'type' => 'japanese',
                'visibility' => 'public',
                'filename' => 'japanese_dragon_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Japanese Dragon Sleeve',
                'description' => 'Traditional Japanese dragon tattoo wrapping around the arm with classic Japanese elements.',
                'primary_style' => 'Traditional',
                'other_styles' => 'Japanese, Sleeve',
                'suggested_placement' => 'Arm',
                'color' => 'Color',
                'tags' => 'japanese, dragon, traditional, sleeve, color',
                'price' => '2000',
                'max_price' => '3000',
                'size_height' => '12',
                'size_width' => '6',
                'cost_per_session' => '500',
                'min_sessions' => '4',
                'max_sessions' => '6',
                'session_time_h' => '5',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Large piece, requires commitment to multiple sessions.',
            ],
            [
                'artist_handle' => $artists[2],
                'type' => 'traditional',
                'visibility' => 'public',
                'filename' => 'neo_traditional_rose_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Neo-Traditional Rose',
                'description' => 'Modern take on traditional rose with enhanced detail and vibrant colors.',
                'primary_style' => 'Traditional',
                'other_styles' => 'Neo-Traditional',
                'suggested_placement' => 'Forearm',
                'color' => 'Color',
                'tags' => 'neo-traditional, rose, traditional, color',
                'price' => '500',
                'max_price' => '700',
                'size_height' => '5',
                'size_width' => '4',
                'cost_per_session' => '350',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Popular design, can be customized.',
            ],
            [
                'artist_handle' => $artists[2],
                'type' => 'traditional',
                'visibility' => 'public',
                'filename' => 'anchor_traditional_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Classic Anchor Tattoo',
                'description' => 'Traditional anchor tattoo with bold lines and classic sailor style.',
                'primary_style' => 'Traditional',
                'other_styles' => 'American Traditional',
                'suggested_placement' => 'Forearm',
                'color' => 'Color',
                'tags' => 'traditional, anchor, sailor, classic, bold',
                'price' => '400',
                'max_price' => '600',
                'size_height' => '4',
                'size_width' => '3',
                'cost_per_session' => '300',
                'min_sessions' => '1',
                'max_sessions' => '2',
                'session_time_h' => '2',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Classic design, timeless appeal.',
            ],
            [
                'artist_handle' => $artists[2],
                'type' => 'japanese',
                'visibility' => 'public',
                'filename' => 'japanese_koi_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Japanese Koi Fish',
                'description' => 'Traditional Japanese koi fish tattoo with water elements and vibrant colors.',
                'primary_style' => 'Traditional',
                'other_styles' => 'Japanese',
                'suggested_placement' => 'Leg',
                'color' => 'Color',
                'tags' => 'japanese, koi, fish, traditional, color',
                'price' => '800',
                'max_price' => '1200',
                'size_height' => '10',
                'size_width' => '5',
                'cost_per_session' => '400',
                'min_sessions' => '2',
                'max_sessions' => '3',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Symbolic design with traditional meaning.',
            ],
        ]);

        // Tattoos for fourth artist (minimalist_emma)
        $tattoos = array_merge($tattoos, [
            [
                'artist_handle' => $artists[3],
                'type' => 'minimalist',
                'visibility' => 'public',
                'filename' => 'fine_line_geometric_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Fine Line Geometric Pattern',
                'description' => 'Delicate fine line geometric pattern with precise linework and minimalist aesthetic.',
                'primary_style' => 'Minimalist',
                'other_styles' => 'Fine Line, Geometric',
                'suggested_placement' => 'Wrist',
                'color' => 'Black',
                'tags' => 'minimalist, fine line, geometric, delicate',
                'price' => '300',
                'max_price' => '500',
                'size_height' => '3',
                'size_width' => '2',
                'cost_per_session' => '250',
                'min_sessions' => '1',
                'max_sessions' => '1',
                'session_time_h' => '2',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Quick session, minimal pain.',
            ],
            [
                'artist_handle' => $artists[3],
                'type' => 'minimalist',
                'visibility' => 'public',
                'filename' => 'single_needle_floral_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Single Needle Floral',
                'description' => 'Delicate single needle floral design with fine lines and minimalist approach.',
                'primary_style' => 'Minimalist',
                'other_styles' => 'Single Needle, Floral',
                'suggested_placement' => 'Ankle',
                'color' => 'Black',
                'tags' => 'minimalist, single needle, floral, delicate',
                'price' => '250',
                'max_price' => '400',
                'size_height' => '2',
                'size_width' => '2',
                'cost_per_session' => '200',
                'min_sessions' => '1',
                'max_sessions' => '1',
                'session_time_h' => '1.5',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Perfect for first tattoo.',
            ],
            [
                'artist_handle' => $artists[3],
                'type' => 'minimalist',
                'visibility' => 'public',
                'filename' => 'dotwork_mandala_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Dotwork Mandala',
                'description' => 'Intricate dotwork mandala with precise stippling technique and minimalist design.',
                'primary_style' => 'Minimalist',
                'other_styles' => 'Dotwork, Mandala',
                'suggested_placement' => 'Back',
                'color' => 'Black',
                'tags' => 'minimalist, dotwork, mandala, stippling',
                'price' => '600',
                'max_price' => '900',
                'size_height' => '6',
                'size_width' => '6',
                'cost_per_session' => '400',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Time-consuming technique, requires patience.',
            ],
            [
                'artist_handle' => $artists[3],
                'type' => 'minimalist',
                'visibility' => 'public',
                'filename' => 'fine_line_script_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Fine Line Script',
                'description' => 'Elegant fine line script tattoo with delicate lettering and minimalist style.',
                'primary_style' => 'Minimalist',
                'other_styles' => 'Fine Line, Script',
                'suggested_placement' => 'Rib',
                'color' => 'Black',
                'tags' => 'minimalist, fine line, script, text',
                'price' => '200',
                'max_price' => '350',
                'size_height' => '4',
                'size_width' => '1',
                'cost_per_session' => '200',
                'min_sessions' => '1',
                'max_sessions' => '1',
                'session_time_h' => '1',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Quick session, bring exact text.',
            ],
            [
                'artist_handle' => $artists[3],
                'type' => 'minimalist',
                'visibility' => 'public',
                'filename' => 'minimalist_animal_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Minimalist Animal Silhouette',
                'description' => 'Simple and elegant animal silhouette with fine lines and minimalist approach.',
                'primary_style' => 'Minimalist',
                'other_styles' => 'Fine Line, Silhouette',
                'suggested_placement' => 'Forearm',
                'color' => 'Black',
                'tags' => 'minimalist, animal, silhouette, fine line',
                'price' => '350',
                'max_price' => '550',
                'size_height' => '4',
                'size_width' => '3',
                'cost_per_session' => '300',
                'min_sessions' => '1',
                'max_sessions' => '1',
                'session_time_h' => '2',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Can be customized with any animal.',
            ],
        ]);

        // Tattoos for fifth artist (colorful_james)
        $tattoos = array_merge($tattoos, [
            [
                'artist_handle' => $artists[4],
                'type' => 'color',
                'visibility' => 'public',
                'filename' => 'colorful_new_school_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'New School Colorful Design',
                'description' => 'Vibrant new school tattoo with bold colors and cartoon-like style.',
                'primary_style' => 'Color',
                'other_styles' => 'New School, Color',
                'suggested_placement' => 'Thigh',
                'color' => 'Color',
                'tags' => 'new school, colorful, vibrant, cartoon',
                'price' => '700',
                'max_price' => '1000',
                'size_height' => '6',
                'size_width' => '5',
                'cost_per_session' => '450',
                'min_sessions' => '2',
                'max_sessions' => '3',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Bold and vibrant design.',
            ],
            [
                'artist_handle' => $artists[4],
                'type' => 'japanese',
                'visibility' => 'public',
                'filename' => 'japanese_color_sleeve_1.jpg',
                'ink' => 'yes',
                'ar' => 'no',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Japanese Color Sleeve',
                'description' => 'Full color Japanese sleeve with traditional elements and vibrant colors.',
                'primary_style' => 'Color',
                'other_styles' => 'Japanese Color, Sleeve',
                'suggested_placement' => 'Arm',
                'color' => 'Color',
                'tags' => 'japanese, color, sleeve, traditional',
                'price' => '2500',
                'max_price' => '3500',
                'size_height' => '14',
                'size_width' => '6',
                'cost_per_session' => '600',
                'min_sessions' => '5',
                'max_sessions' => '7',
                'session_time_h' => '6',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Large project, requires multiple sessions.',
            ],
            [
                'artist_handle' => $artists[4],
                'type' => 'neo-traditional',
                'visibility' => 'public',
                'filename' => 'neo_traditional_color_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Neo-Traditional Colorful Rose',
                'description' => 'Modern neo-traditional rose with enhanced colors and detailed shading.',
                'primary_style' => 'Color',
                'other_styles' => 'Neo-Traditional',
                'suggested_placement' => 'Forearm',
                'color' => 'Color',
                'tags' => 'neo-traditional, rose, color, vibrant',
                'price' => '550',
                'max_price' => '800',
                'size_height' => '5',
                'size_width' => '4',
                'cost_per_session' => '400',
                'min_sessions' => '2',
                'max_sessions' => '2',
                'session_time_h' => '3',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Vibrant colors, long-lasting.',
            ],
            [
                'artist_handle' => $artists[4],
                'type' => 'color',
                'visibility' => 'public',
                'filename' => 'colorful_abstract_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Colorful Abstract Design',
                'description' => 'Bold abstract design with vibrant colors and artistic expression.',
                'primary_style' => 'Color',
                'other_styles' => 'Abstract, Color',
                'suggested_placement' => 'Back',
                'color' => 'Color',
                'tags' => 'abstract, colorful, vibrant, artistic',
                'price' => '900',
                'max_price' => '1300',
                'size_height' => '8',
                'size_width' => '6',
                'cost_per_session' => '500',
                'min_sessions' => '2',
                'max_sessions' => '3',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Unique design, each piece is custom.',
            ],
            [
                'artist_handle' => $artists[4],
                'type' => 'color',
                'visibility' => 'public',
                'filename' => 'tropical_color_1.jpg',
                'ink' => 'yes',
                'ar' => 'yes',
                'repeatable' => 'yes',
                'sensitive' => 'no',
                'title' => 'Tropical Color Design',
                'description' => 'Vibrant tropical design with palm trees and ocean elements in full color.',
                'primary_style' => 'Color',
                'other_styles' => 'Tropical, Nature',
                'suggested_placement' => 'Leg',
                'color' => 'Color',
                'tags' => 'tropical, color, nature, vibrant',
                'price' => '800',
                'max_price' => '1200',
                'size_height' => '10',
                'size_width' => '5',
                'cost_per_session' => '450',
                'min_sessions' => '2',
                'max_sessions' => '3',
                'session_time_h' => '4',
                'currency' => 'USD',
                'price_model' => 'per_session',
                'notes' => 'Perfect for beach lovers.',
            ],
        ]);

        foreach ($tattoos as $tattoo) {
            DB::table('inkjin_tattoos')->insert(array_merge($tattoo, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }

        $this->command->info('Seeded ' . count($tattoos) . ' tattoos successfully!');
    }
}
